import { AgentOpsItem } from './types';
import type { AdvancementFirstDraftPayload } from './advancementTypes';

export function getAdmissionsQueueItems(): AgentOpsItem[] {
  return [
    // Missing Documents - Critical
    {
      id: 'admissions-1',
      type: 'Escalation',
      severity: 'Critical',
      status: 'Open',
      title: 'Missing Transcript - Application Incomplete',
      summary: 'Sarah Chen has not submitted official transcript. Application deadline in 5 days. Transcript Helper Agent unable to verify.',
      person: {
        id: 'person-1',
        name: 'Sarah Chen',
        email: 'sarah.chen@example.edu',
        externalId: 'STU-2024-001',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-transcript-helper',
      agentName: 'Transcript Helper Agent',
      role: 'Admissions',
      sourceSystem: 'SIS',
      createdAt: '2024-01-15T10:30:00Z',
      updatedAt: '2024-01-15T10:35:00Z',
      slaDueAt: '2024-01-15T14:30:00Z',
      createdBy: 'system',
      tags: ['missing-transcript', 'missing-docs', 'verification', 'deadline', 'incomplete-app'],
    },
    {
      id: 'admissions-2',
      type: 'Task',
      severity: 'High',
      status: 'Open',
      title: 'Missing Recommendation Letter',
      summary: 'Alexandra Martinez needs one more recommendation letter to complete application. Reminder sent 3 days ago with no response.',
      person: {
        id: 'person-7',
        name: 'Alexandra Martinez',
        email: 'alex.martinez@example.edu',
        externalId: 'PROSP-2024-012',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-high-intent-prospect',
      agentName: 'High-Intent Prospect Agent',
      role: 'Admissions',
      sourceSystem: 'CRM',
      createdAt: '2024-01-14T14:00:00Z',
      updatedAt: '2024-01-15T09:00:00Z',
      slaDueAt: '2024-01-16T14:00:00Z',
      createdBy: 'agent',
      tags: ['missing-docs', 'recommendation-letter', 'incomplete-app', 'follow-up'],
    },
    {
      id: 'admissions-3',
      type: 'Escalation',
      severity: 'Critical',
      status: 'Open',
      title: 'Missing I-20 and Visa Documents',
      summary: 'Priya Patel missing I-20 and visa documents with deadline approaching in 3 days. International student requires urgent attention.',
      person: {
        id: 'person-5',
        name: 'Priya Patel',
        email: 'priya.patel@example.edu',
        externalId: 'STU-2024-089',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-international-visa',
      agentName: 'International Visa Docs Agent',
      role: 'Admissions',
      sourceSystem: 'SIS',
      createdAt: '2024-01-15T07:00:00Z',
      updatedAt: '2024-01-15T07:05:00Z',
      slaDueAt: '2024-01-15T12:00:00Z',
      createdBy: 'agent',
      tags: ['missing', 'transcript', 'document', 'international', 'deadline', 'escalation'],
    },
    
    // Stalled Applicants
    {
      id: 'admissions-4',
      type: 'Task',
      severity: 'Medium',
      status: 'Open',
      title: 'Application Stalled - No Activity',
      summary: 'Emily Johnson started application 3 weeks ago but has not completed required sections. Last activity was 12 days ago.',
      person: {
        id: 'person-3',
        name: 'Emily Johnson',
        email: 'emily.j@example.edu',
        externalId: 'STU-2024-078',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-high-intent-prospect',
      agentName: 'High-Intent Prospect Agent',
      role: 'Admissions',
      sourceSystem: 'CRM',
      createdAt: '2024-01-14T22:45:00Z',
      updatedAt: '2024-01-15T08:00:00Z',
      slaDueAt: '2024-01-15T10:00:00Z',
      createdBy: 'agent',
      tags: ['stalled', 'inactive', 'no-activity', 'incomplete-app', 'incomplete-application'],
    },
    {
      id: 'admissions-5',
      type: 'Task',
      severity: 'Medium',
      status: 'Open',
      title: 'Follow-up Required: Application Incomplete',
      summary: 'Prospect has not completed application form after 2 weeks of initial contact. Multiple reminders sent with no response.',
      person: {
        id: 'person-11',
        name: 'Jordan Williams',
        email: 'jordan.williams@example.edu',
        externalId: 'PROSP-2024-045',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-high-intent-prospect',
      agentName: 'High-Intent Prospect Agent',
      role: 'Admissions',
      sourceSystem: 'CRM',
      createdAt: '2024-01-13T10:00:00Z',
      updatedAt: '2024-01-15T09:00:00Z',
      slaDueAt: '2024-01-16T14:00:00Z',
      createdBy: 'agent',
      tags: ['stalled', 'task', 'follow-up', 'incomplete', 'no-activity'],
    },
    {
      id: 'admissions-6',
      type: 'OnHold',
      severity: 'Low',
      status: 'Snoozed',
      title: 'Application On Hold - Awaiting Response',
      summary: 'Waiting for applicant to respond to questions about program preferences before proceeding with next steps.',
      person: {
        id: 'person-12',
        name: 'Morgan Davis',
        email: 'morgan.davis@example.edu',
        externalId: 'PROSP-2024-056',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-high-intent-prospect',
      agentName: 'High-Intent Prospect Agent',
      role: 'Admissions',
      sourceSystem: 'Agent Platform',
      createdAt: '2024-01-12T16:00:00Z',
      updatedAt: '2024-01-14T10:00:00Z',
      slaDueAt: '2024-01-17T16:00:00Z',
      createdBy: 'agent',
      tags: ['stalled', 'on-hold', 'awaiting-response', 'inactive'],
    },
    
    // Melt Risk
    {
      id: 'admissions-7',
      type: 'Escalation',
      severity: 'High',
      status: 'Open',
      title: 'Melt Risk: Deposit Deadline Approaching',
      summary: 'Christopher Lee admitted but has not submitted deposit. Deposit deadline is in 4 days. High-intent prospect showing signs of hesitation.',
      person: {
        id: 'person-10',
        name: 'Christopher Lee',
        email: 'chris.lee@example.edu',
        externalId: 'STU-2024-023',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-high-intent-prospect',
      agentName: 'High-Intent Prospect Agent',
      role: 'Admissions',
      sourceSystem: 'Financial Aid System',
      createdAt: '2024-01-15T06:00:00Z',
      updatedAt: '2024-01-15T09:30:00Z',
      slaDueAt: '2024-01-16T18:00:00Z',
      createdBy: 'agent',
      tags: ['melt-risk', 'deposit-window', 'admitted-no-deposit', 'high-intent', 'deposit'],
    },
    {
      id: 'admissions-8',
      type: 'Task',
      severity: 'High',
      status: 'Open',
      title: 'Admitted Student - No Deposit',
      summary: 'Taylor Brown was admitted 10 days ago but has not submitted enrollment deposit. Follow-up needed to prevent melt.',
      person: {
        id: 'person-13',
        name: 'Taylor Brown',
        email: 'taylor.brown@example.edu',
        externalId: 'STU-2024-067',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-high-intent-prospect',
      agentName: 'High-Intent Prospect Agent',
      role: 'Admissions',
      sourceSystem: 'CRM',
      createdAt: '2024-01-14T11:00:00Z',
      updatedAt: '2024-01-15T08:00:00Z',
      slaDueAt: '2024-01-16T11:00:00Z',
      createdBy: 'agent',
      tags: ['melt-risk', 'admitted', 'deposit', 'admitted-no-deposit'],
    },
    
    // Other Admissions Items
    {
      id: 'admissions-9',
      type: 'HumanReview',
      severity: 'High',
      status: 'InProgress',
      title: 'Human Review Required - Scholarship Eligibility',
      summary: 'Agent flagged applicant for scholarship review based on new criteria. Requires manual review before proceeding.',
      person: {
        id: 'person-14',
        name: 'Riley Garcia',
        email: 'riley.garcia@example.edu',
        externalId: 'STU-2024-078',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-high-intent-prospect',
      agentName: 'High-Intent Prospect Agent',
      role: 'Admissions',
      sourceSystem: 'Financial Aid System',
      createdAt: '2024-01-15T08:00:00Z',
      updatedAt: '2024-01-15T09:30:00Z',
      slaDueAt: '2024-01-16T18:00:00Z',
      createdBy: 'agent',
      assignedTo: 'user-123',
      tags: ['scholarship', 'financial-aid', 'review', 'human-review', 'approval-needed'],
    },
    {
      id: 'admissions-10',
      type: 'Error',
      severity: 'Medium',
      status: 'Open',
      title: 'API Connection Failure - Transcript Verification',
      summary: 'Transcript Helper Agent failed to connect to SIS API during transcript verification for applicant.',
      person: {
        id: 'person-15',
        name: 'Casey Martinez',
        email: 'casey.martinez@example.edu',
        externalId: 'STU-2024-089',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-transcript-helper',
      agentName: 'Transcript Helper Agent',
      role: 'Admissions',
      sourceSystem: 'SIS',
      createdAt: '2024-01-15T11:00:00Z',
      updatedAt: '2024-01-15T11:05:00Z',
      slaDueAt: '2024-01-15T13:00:00Z',
      createdBy: 'system',
      tags: ['api-error', 'sis-integration', 'transcript', 'missing'],
    },
    {
      id: 'admissions-11',
      type: 'Guardrail',
      severity: 'Medium',
      status: 'Open',
      title: 'Tone Guardrail Triggered',
      summary: 'Agent response exceeded tone threshold (too formal) for prospect communication. Requires review before sending.',
      person: {
        id: 'person-16',
        name: 'Avery Johnson',
        email: 'avery.johnson@example.edu',
        externalId: 'PROSP-2024-090',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-high-intent-prospect',
      agentName: 'High-Intent Prospect Agent',
      role: 'Admissions',
      sourceSystem: 'Agent Platform',
      createdAt: '2024-01-15T08:45:00Z',
      updatedAt: '2024-01-15T08:46:00Z',
      slaDueAt: '2024-01-15T12:45:00Z',
      createdBy: 'agent',
      guardrailId: 'guardrail-tone',
      tags: ['tone', 'content-filter', 'guardrail'],
    },
    {
      id: 'admissions-12',
      type: 'QuietHours',
      severity: 'Low',
      status: 'Snoozed',
      title: 'Message Blocked - Quiet Hours',
      summary: 'Attempted to send message outside of allowed hours (9 PM - 8 AM). Will be sent automatically at 8 AM.',
      person: {
        id: 'person-17',
        name: 'Quinn Anderson',
        email: 'quinn.anderson@example.edu',
        externalId: 'PROSP-2024-091',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-high-intent-prospect',
      agentName: 'High-Intent Prospect Agent',
      role: 'Admissions',
      sourceSystem: 'Agent Platform',
      createdAt: '2024-01-14T22:45:00Z',
      updatedAt: '2024-01-15T08:00:00Z',
      slaDueAt: '2024-01-15T10:00:00Z',
      createdBy: 'agent',
      tags: ['quiet-hours', 'scheduled'],
    },
  ];
}

export function getAdvancementPipelineQueueItems(): AgentOpsItem[] {
  const now = new Date();
  const yesterday = new Date(now.getTime() - 24 * 60 * 60 * 1000);
  const lastWeek = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
  const lastMonth = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
  const twoMonthsAgo = new Date(now.getTime() - 60 * 24 * 60 * 60 * 1000);

  return [
    // First Draft Items (6 items)
    {
      id: 'advancement-first-draft-1',
      type: 'Task',
      severity: 'High',
      status: 'Open',
      title: 'First Draft: Follow-up with major donor',
      summary: 'AI has drafted personalized outreach email for major donor. Review and send to maintain relationship momentum.',
      person: {
        id: 'donor-1',
        name: 'Margaret Thompson',
        email: 'margaret.thompson@example.com',
        externalId: 'DONOR-2023-045',
        primaryRole: 'Advancement',
      },
      agentId: 'agent-donor-warmup',
      agentName: 'Donor Warm-Up Agent',
      role: 'Advancement',
      sourceSystem: 'CRM',
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
      slaDueAt: new Date(now.getTime() + 24 * 60 * 60 * 1000).toISOString(),
      createdBy: 'agent',
      tags: ['first-draft', 'major-donor', 'stewardship'],
      detailView: 'first-draft',
      payload: {
        donor: {
          id: 'donor-1',
          name: 'Margaret Thompson',
          email: 'margaret.thompson@example.com',
          phone: '+1 (555) 123-4567',
          location: 'San Francisco, CA',
          lastGiftAmount: 50000,
          lastGiftDate: lastMonth.toISOString(),
          lifetimeGiving: 250000,
          numberOfGifts: 12,
          lastActionLabel: 'Thank you call',
          lastActionDate: lastWeek.toISOString(),
          assignedOfficer: 'Sarah Johnson',
          crmId: 'CRM-12345',
        },
        reasonForOutreach: 'Margaret made a significant gift last month and has been a consistent supporter. This is a stewardship follow-up to acknowledge her generosity and share impact updates.',
        timeline: [
          {
            id: 'timeline-1',
            date: lastMonth.toISOString(),
            type: 'gift',
            summary: 'Gift of $50,000 received for scholarship fund',
          },
          {
            id: 'timeline-2',
            date: lastWeek.toISOString(),
            type: 'call',
            summary: 'Thank you call from Sarah Johnson',
          },
          {
            id: 'timeline-3',
            date: twoMonthsAgo.toISOString(),
            type: 'email',
            summary: 'Sent impact report on scholarship recipients',
          },
        ],
        drafts: [
          {
            id: 'draft-1',
            label: 'Warm & Personal',
            subject: 'Thank you for your incredible generosity, Margaret',
            body: `Dear Margaret,

Thank you so much for your recent gift of $50,000 to our scholarship fund. Your generosity is making a real difference in the lives of our students.

I wanted to share a quick update: your gift has already helped three students this semester who otherwise wouldn't have been able to continue their education. One of them, Maria, wrote to us saying, "This scholarship didn't just help me financially—it gave me hope."

We're so grateful for your continued support. Would you be interested in meeting some of the students your generosity has helped? I'd love to arrange a visit when it's convenient for you.

With deepest gratitude,
Sarah Johnson
Development Officer`,
          },
          {
            id: 'draft-2',
            label: 'Impact-Focused',
            subject: 'Your gift is already changing lives',
            body: `Dear Margaret,

Your recent gift of $50,000 to our scholarship fund is already having an impact. Three students have received support this semester thanks to your generosity.

I'd love to share more about how your gift is being used and introduce you to some of the students you're helping. Would you be available for a brief call or visit in the coming weeks?

Thank you for your continued partnership in our mission.

Best regards,
Sarah Johnson`,
          },
        ],
        recommendedChannel: 'email',
      } as AdvancementFirstDraftPayload,
    },
    {
      id: 'advancement-first-draft-2',
      type: 'Task',
      severity: 'High',
      status: 'Open',
      title: 'First Draft: Re-engage lapsed donor',
      summary: 'Donor has not given in 18 months. AI drafted re-engagement email to restore relationship.',
      person: {
        id: 'donor-2',
        name: 'Robert Chen',
        email: 'robert.chen@example.com',
        externalId: 'DONOR-2022-089',
        primaryRole: 'Advancement',
      },
      agentId: 'agent-donor-warmup',
      agentName: 'Donor Warm-Up Agent',
      role: 'Advancement',
      sourceSystem: 'CRM',
      createdAt: yesterday.toISOString(),
      updatedAt: yesterday.toISOString(),
      slaDueAt: new Date(now.getTime() + 48 * 60 * 60 * 1000).toISOString(),
      createdBy: 'agent',
      tags: ['first-draft', 'lybunt', 're-engagement', 'stalled'],
      detailView: 'first-draft',
      payload: {
        donor: {
          id: 'donor-2',
          name: 'Robert Chen',
          email: 'robert.chen@example.com',
          phone: '+1 (555) 234-5678',
          location: 'New York, NY',
          lastGiftAmount: 10000,
          lastGiftDate: twoMonthsAgo.toISOString(),
          lifetimeGiving: 75000,
          numberOfGifts: 8,
          lastActionLabel: 'Event invitation',
          lastActionDate: lastMonth.toISOString(),
          assignedOfficer: 'Michael Davis',
          crmId: 'CRM-23456',
        },
        reasonForOutreach: "Robert was a consistent annual donor but hasn't given in 18 months. This is a re-engagement opportunity to restore the relationship and understand if there are any concerns or changes in his giving capacity.",
        timeline: [
          {
            id: 'timeline-4',
            date: twoMonthsAgo.toISOString(),
            type: 'gift',
            summary: 'Last gift of $10,000 received',
          },
          {
            id: 'timeline-5',
            date: lastMonth.toISOString(),
            type: 'email',
            summary: 'Sent invitation to annual gala',
          },
          {
            id: 'timeline-6',
            date: new Date(now.getTime() - 90 * 24 * 60 * 60 * 1000).toISOString(),
            type: 'call',
            summary: 'Thank you call for previous gift',
          },
        ],
        drafts: [
          {
            id: 'draft-3',
            label: 'Re-engagement',
            subject: 'We miss you, Robert',
            body: `Dear Robert,

I hope this message finds you well. It's been a while since we've connected, and I wanted to reach out personally.

Your past support has meant so much to our students and programs. I know life gets busy, but I wanted to check in and see how you're doing. Is there anything we could be doing differently to stay connected?

I'd love to catch up and share what's been happening at the university. Would you be open to a brief call?

Warm regards,
Michael Davis
Development Officer`,
          },
        ],
        recommendedChannel: 'email',
      } as AdvancementFirstDraftPayload,
    },
    {
      id: 'advancement-first-draft-3',
      type: 'Task',
      severity: 'Medium',
      status: 'Open',
      title: 'First Draft: Proposal follow-up',
      summary: 'Proposal sent 2 weeks ago with no response. AI drafted follow-up email to advance the conversation.',
      person: {
        id: 'donor-3',
        name: 'Patricia Williams',
        email: 'patricia.williams@example.com',
        externalId: 'DONOR-2023-156',
        primaryRole: 'Advancement',
      },
      agentId: 'agent-proposal-builder',
      agentName: 'Proposal Builder Agent',
      role: 'Advancement',
      sourceSystem: 'CRM',
      createdAt: yesterday.toISOString(),
      updatedAt: yesterday.toISOString(),
      slaDueAt: new Date(now.getTime() + 72 * 60 * 60 * 1000).toISOString(),
      createdBy: 'agent',
      tags: ['first-draft', 'proposal', 'follow-up', 'advance-proposals'],
      detailView: 'first-draft',
      payload: {
        donor: {
          id: 'donor-3',
          name: 'Patricia Williams',
          email: 'patricia.williams@example.com',
          phone: '+1 (555) 345-6789',
          location: 'Chicago, IL',
          lastGiftAmount: 25000,
          lastGiftDate: lastMonth.toISOString(),
          lifetimeGiving: 150000,
          numberOfGifts: 15,
          lastActionLabel: 'Proposal sent',
          lastActionDate: lastWeek.toISOString(),
          assignedOfficer: 'Jennifer Martinez',
          crmId: 'CRM-34567',
        },
        reasonForOutreach: 'Proposal for a named scholarship was sent 2 weeks ago with no response. This follow-up will check in, answer any questions, and move the conversation forward.',
        timeline: [
          {
            id: 'timeline-7',
            date: lastWeek.toISOString(),
            type: 'email',
            summary: 'Proposal for $100,000 named scholarship sent',
          },
          {
            id: 'timeline-8',
            date: lastMonth.toISOString(),
            type: 'gift',
            summary: 'Gift of $25,000 received',
          },
          {
            id: 'timeline-9',
            date: new Date(now.getTime() - 45 * 24 * 60 * 60 * 1000).toISOString(),
            type: 'meeting',
            summary: 'In-person meeting to discuss giving priorities',
          },
        ],
        drafts: [
          {
            id: 'draft-4',
            label: 'Follow-up',
            subject: 'Following up on the scholarship proposal',
            body: `Dear Patricia,

I wanted to follow up on the proposal I sent last week for the named scholarship opportunity. I know you're busy, so I wanted to check in and see if you have any questions.

The proposal outlines how a $100,000 gift would create a lasting impact through the Patricia Williams Scholarship Fund. I'd be happy to discuss any aspects of this opportunity that you'd like to explore further.

Would you be available for a brief call this week? I'm flexible with timing.

Best regards,
Jennifer Martinez
Development Officer`,
          },
        ],
        recommendedChannel: 'email',
      } as AdvancementFirstDraftPayload,
    },
    {
      id: 'advancement-first-draft-4',
      type: 'Task',
      severity: 'Medium',
      status: 'Open',
      title: 'First Draft: Stewardship thank you',
      summary: 'Recent gift received. AI drafted personalized thank you email to acknowledge generosity.',
      person: {
        id: 'donor-4',
        name: 'David Kim',
        email: 'david.kim@example.com',
        externalId: 'DONOR-2024-012',
        primaryRole: 'Advancement',
      },
      agentId: 'agent-donor-warmup',
      agentName: 'Donor Warm-Up Agent',
      role: 'Advancement',
      sourceSystem: 'CRM',
      createdAt: yesterday.toISOString(),
      updatedAt: yesterday.toISOString(),
      slaDueAt: new Date(now.getTime() + 24 * 60 * 60 * 1000).toISOString(),
      createdBy: 'agent',
      tags: ['first-draft', 'stewardship', 'thank-you', 'stewardship-followups'],
      detailView: 'first-draft',
      payload: {
        donor: {
          id: 'donor-4',
          name: 'David Kim',
          email: 'david.kim@example.com',
          phone: '+1 (555) 456-7890',
          location: 'Seattle, WA',
          lastGiftAmount: 5000,
          lastGiftDate: yesterday.toISOString(),
          lifetimeGiving: 35000,
          numberOfGifts: 6,
          lastActionLabel: 'Gift received',
          lastActionDate: yesterday.toISOString(),
          assignedOfficer: 'Sarah Johnson',
          crmId: 'CRM-45678',
        },
        reasonForOutreach: 'David made a gift yesterday. This is a timely stewardship thank you to acknowledge his generosity and share how the gift will be used.',
        timeline: [
          {
            id: 'timeline-10',
            date: yesterday.toISOString(),
            type: 'gift',
            summary: 'Gift of $5,000 received for general fund',
          },
          {
            id: 'timeline-11',
            date: lastMonth.toISOString(),
            type: 'email',
            summary: 'Sent annual impact report',
          },
        ],
        drafts: [
          {
            id: 'draft-5',
            label: 'Thank You',
            subject: 'Thank you for your generous gift, David',
            body: `Dear David,

Thank you so much for your generous gift of $5,000. Your support helps us continue our mission of providing exceptional education and opportunities for our students.

Your gift will go directly to supporting our general fund, which allows us to respond quickly to the most pressing needs across campus—from student scholarships to program enhancements.

We're truly grateful for your continued partnership.

With appreciation,
Sarah Johnson
Development Officer`,
          },
        ],
        recommendedChannel: 'email',
      } as AdvancementFirstDraftPayload,
    },
    {
      id: 'advancement-first-draft-5',
      type: 'Task',
      severity: 'High',
      status: 'Open',
      title: 'First Draft: Meeting prep brief',
      summary: 'Donor meeting scheduled in 2 days. AI drafted meeting brief and talking points.',
      person: {
        id: 'donor-5',
        name: 'Elizabeth Anderson',
        email: 'elizabeth.anderson@example.com',
        externalId: 'DONOR-2023-234',
        primaryRole: 'Advancement',
      },
      agentId: 'agent-proposal-builder',
      agentName: 'Proposal Builder Agent',
      role: 'Advancement',
      sourceSystem: 'CRM',
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
      slaDueAt: new Date(now.getTime() + 48 * 60 * 60 * 1000).toISOString(),
      createdBy: 'agent',
      tags: ['first-draft', 'meeting', 'brief', 'prep-briefs'],
      detailView: 'first-draft',
      payload: {
        donor: {
          id: 'donor-5',
          name: 'Elizabeth Anderson',
          email: 'elizabeth.anderson@example.com',
          phone: '+1 (555) 567-8901',
          location: 'Boston, MA',
          lastGiftAmount: 15000,
          lastGiftDate: lastMonth.toISOString(),
          lifetimeGiving: 120000,
          numberOfGifts: 10,
          lastActionLabel: 'Meeting scheduled',
          lastActionDate: lastWeek.toISOString(),
          assignedOfficer: 'Michael Davis',
          crmId: 'CRM-56789',
        },
        reasonForOutreach: 'Meeting scheduled in 2 days to discuss a major gift opportunity. This brief provides talking points and context to ensure a productive conversation.',
        timeline: [
          {
            id: 'timeline-12',
            date: lastWeek.toISOString(),
            type: 'call',
            summary: 'Meeting scheduled for upcoming week',
          },
          {
            id: 'timeline-13',
            date: lastMonth.toISOString(),
            type: 'gift',
            summary: 'Gift of $15,000 received',
          },
          {
            id: 'timeline-14',
            date: new Date(now.getTime() - 60 * 24 * 60 * 60 * 1000).toISOString(),
            type: 'event',
            summary: 'Attended annual gala',
          },
        ],
        drafts: [
          {
            id: 'draft-6',
            label: 'Meeting Brief',
            subject: 'Meeting Brief: Elizabeth Anderson - Major Gift Discussion',
            body: `Meeting Context:
- Elizabeth has been a consistent supporter with $120,000 in lifetime giving
- Recently attended annual gala and expressed interest in supporting student success programs
- Meeting goal: Discuss a $50,000 gift opportunity for the Student Success Initiative

Talking Points:
1. Thank her for her continued support and recent attendance at the gala
2. Share impact of her past gifts on student success programs
3. Present the Student Success Initiative opportunity
4. Discuss how a $50,000 gift would create lasting impact
5. Address any questions or concerns

Next Steps:
- Send follow-up email within 24 hours of meeting
- If interested, prepare formal proposal within 1 week`,
          },
        ],
        recommendedChannel: 'email',
      } as AdvancementFirstDraftPayload,
    },
    {
      id: 'advancement-first-draft-6',
      type: 'Task',
      severity: 'Medium',
      status: 'Open',
      title: 'First Draft: Event invitation follow-up',
      summary: "Donor invited to event but hasn't RSVP'd. AI drafted follow-up to encourage attendance.",
      person: {
        id: 'donor-6',
        name: 'James Wilson',
        email: 'james.wilson@example.com',
        externalId: 'DONOR-2023-345',
        primaryRole: 'Advancement',
      },
      agentId: 'agent-donor-warmup',
      agentName: 'Donor Warm-Up Agent',
      role: 'Advancement',
      sourceSystem: 'CRM',
      createdAt: yesterday.toISOString(),
      updatedAt: yesterday.toISOString(),
      slaDueAt: new Date(now.getTime() + 72 * 60 * 60 * 1000).toISOString(),
      createdBy: 'agent',
      tags: ['first-draft', 'event', 'invitation', 'follow-up'],
      detailView: 'first-draft',
      payload: {
        donor: {
          id: 'donor-6',
          name: 'James Wilson',
          email: 'james.wilson@example.com',
          phone: '+1 (555) 678-9012',
          location: 'Los Angeles, CA',
          lastGiftAmount: 7500,
          lastGiftDate: lastMonth.toISOString(),
          lifetimeGiving: 45000,
          numberOfGifts: 7,
          lastActionLabel: 'Event invitation sent',
          lastActionDate: lastWeek.toISOString(),
          assignedOfficer: 'Jennifer Martinez',
          crmId: 'CRM-67890',
        },
        reasonForOutreach: "James was invited to the annual scholarship dinner but hasn't RSVP'd yet. This follow-up will encourage attendance and provide additional event details.",
        timeline: [
          {
            id: 'timeline-15',
            date: lastWeek.toISOString(),
            type: 'email',
            summary: 'Sent invitation to annual scholarship dinner',
          },
          {
            id: 'timeline-16',
            date: lastMonth.toISOString(),
            type: 'gift',
            summary: 'Gift of $7,500 received',
          },
        ],
        drafts: [
          {
            id: 'draft-7',
            label: 'Follow-up',
            subject: 'Following up on the scholarship dinner invitation',
            body: `Dear James,

I wanted to follow up on the invitation I sent last week for our annual scholarship dinner on March 15th. I hope you'll be able to join us for what promises to be an inspiring evening.

The dinner will feature stories from scholarship recipients whose lives have been transformed by the generosity of donors like you. It's always a highlight of our year, and I think you'd really enjoy it.

If you have any questions or would like more information, please don't hesitate to reach out. I'd love to see you there!

Best regards,
Jennifer Martinez
Development Officer`,
          },
        ],
        recommendedChannel: 'email',
      } as AdvancementFirstDraftPayload,
    },

    // Other Pipeline Items (6 items)
    {
      id: 'advancement-1',
      type: 'Task',
      severity: 'Medium',
      status: 'Open',
      title: 'Stalled Opportunity - No Activity',
      summary: 'Prospect has not responded to outreach in 21 days. Opportunity may be stalling.',
      person: {
        id: 'donor-7',
        name: 'Thomas Brown',
        email: 'thomas.brown@example.com',
        externalId: 'PROSP-2024-078',
        primaryRole: 'Advancement',
      },
      agentId: 'agent-donor-warmup',
      agentName: 'Donor Warm-Up Agent',
      role: 'Advancement',
      sourceSystem: 'CRM',
      createdAt: lastWeek.toISOString(),
      updatedAt: lastWeek.toISOString(),
      slaDueAt: new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000).toISOString(),
      createdBy: 'agent',
      tags: ['stalled', 'inactive', 'no-activity', 'overdue', 're-engage-stalled'],
    },
    {
      id: 'advancement-2',
      type: 'Task',
      severity: 'High',
      status: 'Open',
      title: 'Meeting Prep Required',
      summary: 'Donor meeting scheduled in 48 hours. Brief needs to be prepared with talking points and proposal details.',
      person: {
        id: 'donor-8',
        name: 'Linda Garcia',
        email: 'linda.garcia@example.com',
        externalId: 'DONOR-2023-456',
        primaryRole: 'Advancement',
      },
      agentId: 'agent-proposal-builder',
      agentName: 'Proposal Builder Agent',
      role: 'Advancement',
      sourceSystem: 'CRM',
      createdAt: yesterday.toISOString(),
      updatedAt: yesterday.toISOString(),
      slaDueAt: new Date(now.getTime() + 48 * 60 * 60 * 1000).toISOString(),
      createdBy: 'agent',
      tags: ['meeting', 'brief', 'prep', 'upcoming-meeting', 'prep-briefs'],
    },
    {
      id: 'advancement-3',
      type: 'Task',
      severity: 'High',
      status: 'Open',
      title: 'Proposal Stuck in Review',
      summary: 'Proposal sent 3 weeks ago with close date inside 30 days. Needs follow-up to advance.',
      person: {
        id: 'donor-9',
        name: 'Richard Martinez',
        email: 'richard.martinez@example.com',
        externalId: 'DONOR-2023-567',
        primaryRole: 'Advancement',
      },
      agentId: 'agent-proposal-builder',
      agentName: 'Proposal Builder Agent',
      role: 'Advancement',
      sourceSystem: 'CRM',
      createdAt: lastWeek.toISOString(),
      updatedAt: lastWeek.toISOString(),
      slaDueAt: new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000).toISOString(),
      createdBy: 'agent',
      tags: ['proposal', 'review', 'stuck', 'late-stage', 'advance-proposals'],
    },
    {
      id: 'advancement-4',
      type: 'Task',
      severity: 'Medium',
      status: 'Open',
      title: 'Stewardship Follow-up Needed',
      summary: 'Gift received 5 days ago but no thank you sequence has been logged. Stewardship follow-up required.',
      person: {
        id: 'donor-10',
        name: 'Susan Lee',
        email: 'susan.lee@example.com',
        externalId: 'DONOR-2024-089',
        primaryRole: 'Advancement',
      },
      agentId: 'agent-donor-warmup',
      agentName: 'Donor Warm-Up Agent',
      role: 'Advancement',
      sourceSystem: 'CRM',
      createdAt: yesterday.toISOString(),
      updatedAt: yesterday.toISOString(),
      slaDueAt: new Date(now.getTime() + 3 * 24 * 60 * 60 * 1000).toISOString(),
      createdBy: 'agent',
      tags: ['stewardship', 'thank-you', 'follow-up', 'gift', 'stewardship-followups'],
    },
    {
      id: 'advancement-5',
      type: 'FrequencyCap',
      severity: 'Low',
      status: 'Open',
      title: 'Frequency Cap Reached',
      summary: 'Maximum messages per week limit reached for this prospect. Will reset in 2 days.',
      person: {
        id: 'donor-11',
        name: 'William Taylor',
        email: 'william.taylor@example.com',
        externalId: 'PROSP-2024-123',
        primaryRole: 'Advancement',
      },
      agentId: 'agent-donor-warmup',
      agentName: 'Donor Warm-Up Agent',
      role: 'Advancement',
      sourceSystem: 'Agent Platform',
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
      slaDueAt: new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000).toISOString(),
      createdBy: 'system',
      tags: ['frequency-cap', 'rate-limit'],
    },
    {
      id: 'advancement-6',
      type: 'Guardrail',
      severity: 'Medium',
      status: 'Open',
      title: 'Tone Guardrail Triggered',
      summary: 'Agent response exceeded tone threshold (too formal) for prospect communication.',
      person: {
        id: 'donor-12',
        name: 'Nancy White',
        email: 'nancy.white@example.com',
        externalId: 'PROSP-2024-234',
        primaryRole: 'Advancement',
      },
      agentId: 'agent-donor-warmup',
      agentName: 'Donor Warm-Up Agent',
      role: 'Advancement',
      sourceSystem: 'Agent Platform',
      createdAt: yesterday.toISOString(),
      updatedAt: yesterday.toISOString(),
      slaDueAt: new Date(now.getTime() + 24 * 60 * 60 * 1000).toISOString(),
      createdBy: 'agent',
      guardrailId: 'guardrail-tone',
      tags: ['tone', 'content-filter', 'guardrail'],
    },
  ];
}

export function getMockAgentOpsItemsForWorkspace(workspaceId: string): AgentOpsItem[] {
  switch (workspaceId) {
    case 'admissions':
      return getAdmissionsQueueItems();
    case 'advancement':
      return getAdvancementPipelineQueueItems();
    default:
      return getMockAgentOpsItems();
  }
}

export function getMockAgentOpsItems(): AgentOpsItem[] {
  return [
    {
      id: 'item-1',
      type: 'Error',
      severity: 'Critical',
      status: 'Open',
      title: 'API Connection Failure',
      summary: 'Agent "Transcript Helper" failed to connect to SIS API during transcript verification',
      person: {
        id: 'person-1',
        name: 'Sarah Chen',
        email: 'sarah.chen@example.edu',
        externalId: 'STU-2024-001',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-transcript-helper',
      agentName: 'Transcript Helper Agent',
      role: 'Admissions',
      sourceSystem: 'SIS',
      createdAt: '2024-01-15T10:30:00Z',
      updatedAt: '2024-01-15T10:35:00Z',
      slaDueAt: '2024-01-15T14:30:00Z',
      createdBy: 'system',
      tags: ['api-error', 'sis-integration'],
    },
    {
      id: 'item-2',
      type: 'Guardrail',
      severity: 'High',
      status: 'Open',
      title: 'Sensitive Content Detected',
      summary: 'Agent attempted to send message containing potentially sensitive financial information',
      person: {
        id: 'person-2',
        name: 'Michael Rodriguez',
        email: 'm.rodriguez@example.edu',
        externalId: 'STU-2024-042',
        primaryRole: 'Student Success',
      },
      agentId: 'agent-registration-requirements',
      agentName: 'Registration Requirements Agent',
      role: 'Registrar',
      sourceSystem: 'Agent Platform',
      createdAt: '2024-01-15T09:15:00Z',
      updatedAt: '2024-01-15T09:20:00Z',
      slaDueAt: '2024-01-15T13:15:00Z',
      createdBy: 'agent',
      guardrailId: 'guardrail-financial-info',
      tags: ['content-filter', 'pii'],
    },
    {
      id: 'item-3',
      type: 'QuietHours',
      severity: 'Low',
      status: 'Snoozed',
      title: 'Message Blocked - Quiet Hours',
      summary: 'Attempted to send message outside of allowed hours (9 PM - 8 AM)',
      person: {
        id: 'person-3',
        name: 'Emily Johnson',
        email: 'emily.j@example.edu',
        externalId: 'STU-2024-078',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-high-intent-prospect',
      agentName: 'High-Intent Prospect Agent',
      role: 'Admissions',
      sourceSystem: 'Agent Platform',
      createdAt: '2024-01-14T22:45:00Z',
      updatedAt: '2024-01-15T08:00:00Z',
      slaDueAt: '2024-01-15T10:00:00Z',
      createdBy: 'agent',
      tags: ['quiet-hours', 'scheduled'],
    },
    {
      id: 'item-4',
      type: 'DoNotEngage',
      severity: 'Medium',
      status: 'Resolved',
      title: 'Do Not Engage Rule Triggered',
      summary: 'Person has active DNE rule for email channel',
      person: {
        id: 'person-4',
        name: 'David Kim',
        email: 'david.kim@example.edu',
        externalId: 'STU-2023-156',
        primaryRole: 'Career Services',
      },
      agentId: 'agent-donor-warmup',
      agentName: 'Donor Warm-Up Agent',
      role: 'Advancement',
      sourceSystem: 'DNE System',
      createdAt: '2024-01-15T08:20:00Z',
      updatedAt: '2024-01-15T08:25:00Z',
      createdBy: 'system',
      tags: ['dne', 'email-block'],
    },
    {
      id: 'item-5',
      type: 'HumanReview',
      severity: 'High',
      status: 'InProgress',
      title: 'Human Review Required',
      summary: 'Agent generated response that requires human approval before sending',
      person: {
        id: 'person-1',
        name: 'Sarah Chen',
        email: 'sarah.chen@example.edu',
        externalId: 'STU-2024-001',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-transcript-helper',
      agentName: 'Transcript Helper Agent',
      role: 'Admissions',
      sourceSystem: 'Agent Platform',
      createdAt: '2024-01-15T11:00:00Z',
      updatedAt: '2024-01-15T11:05:00Z',
      slaDueAt: '2024-01-15T13:00:00Z',
      createdBy: 'agent',
      assignedTo: 'user-123',
      tags: ['human-review', 'approval-needed'],
    },
    {
      id: 'item-6',
      type: 'Escalation',
      severity: 'Critical',
      status: 'Open',
      title: 'Escalation: Missing Critical Documents',
      summary: 'Student missing I-20 and visa documents with deadline approaching in 3 days',
      person: {
        id: 'person-5',
        name: 'Priya Patel',
        email: 'priya.patel@example.edu',
        externalId: 'STU-2024-089',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-international-visa',
      agentName: 'International Visa Docs Agent',
      role: 'Admissions',
      sourceSystem: 'SIS',
      createdAt: '2024-01-15T07:00:00Z',
      updatedAt: '2024-01-15T07:05:00Z',
      slaDueAt: '2024-01-15T12:00:00Z',
      createdBy: 'agent',
      tags: ['escalation', 'deadline', 'international'],
    },
    {
      id: 'item-7',
      type: 'FrequencyCap',
      severity: 'Low',
      status: 'Open',
      title: 'Frequency Cap Reached',
      summary: 'Maximum messages per week limit reached for this person',
      person: {
        id: 'person-6',
        name: 'James Wilson',
        email: 'james.wilson@example.edu',
        externalId: 'STU-2023-234',
        primaryRole: 'Alumni Engagement',
      },
      agentId: 'agent-donor-warmup',
      agentName: 'Donor Warm-Up Agent',
      role: 'Advancement',
      sourceSystem: 'Agent Platform',
      createdAt: '2024-01-15T09:30:00Z',
      updatedAt: '2024-01-15T09:30:00Z',
      createdBy: 'system',
      tags: ['frequency-cap', 'rate-limit'],
    },
    {
      id: 'item-8',
      type: 'Task',
      severity: 'Medium',
      status: 'Open',
      title: 'Follow-up Required: Application Incomplete',
      summary: 'Prospect has not completed application form after 2 weeks of initial contact',
      person: {
        id: 'person-7',
        name: 'Alexandra Martinez',
        email: 'alex.martinez@example.edu',
        externalId: 'PROSP-2024-012',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-high-intent-prospect',
      agentName: 'High-Intent Prospect Agent',
      role: 'Admissions',
      sourceSystem: 'CRM',
      createdAt: '2024-01-14T14:00:00Z',
      updatedAt: '2024-01-15T09:00:00Z',
      slaDueAt: '2024-01-16T14:00:00Z',
      createdBy: 'agent',
      tags: ['task', 'follow-up', 'incomplete'],
    },
    {
      id: 'item-9',
      type: 'OnHold',
      severity: 'Low',
      status: 'Snoozed',
      title: 'Item On Hold - Awaiting Response',
      summary: 'Waiting for person to respond before proceeding with next action',
      person: {
        id: 'person-2',
        name: 'Michael Rodriguez',
        email: 'm.rodriguez@example.edu',
        externalId: 'STU-2024-042',
        primaryRole: 'Student Success',
      },
      agentId: 'agent-registration-requirements',
      agentName: 'Registration Requirements Agent',
      role: 'Registrar',
      sourceSystem: 'Agent Platform',
      createdAt: '2024-01-13T16:00:00Z',
      updatedAt: '2024-01-14T10:00:00Z',
      slaDueAt: '2024-01-17T16:00:00Z',
      createdBy: 'agent',
      tags: ['on-hold', 'awaiting-response'],
    },
    {
      id: 'item-10',
      type: 'Error',
      severity: 'High',
      status: 'Open',
      title: 'Data Validation Error',
      summary: 'Invalid email format detected in person record',
      person: {
        id: 'person-8',
        name: 'Robert Taylor',
        email: 'robert.taylor@example.edu',
        externalId: 'STU-2024-056',
        primaryRole: 'Career Services',
      },
      agentId: 'agent-donor-warmup',
      agentName: 'Donor Warm-Up Agent',
      role: 'Advancement',
      sourceSystem: 'CRM',
      createdAt: '2024-01-15T10:00:00Z',
      updatedAt: '2024-01-15T10:01:00Z',
      slaDueAt: '2024-01-15T14:00:00Z',
      createdBy: 'system',
      tags: ['data-quality', 'validation'],
    },
    {
      id: 'item-11',
      type: 'Guardrail',
      severity: 'Medium',
      status: 'Open',
      title: 'Tone Guardrail Triggered',
      summary: 'Agent response exceeded tone threshold (too formal)',
      person: {
        id: 'person-9',
        name: 'Lisa Anderson',
        email: 'lisa.anderson@example.edu',
        externalId: 'ALUM-2020-045',
        primaryRole: 'Alumni Engagement',
      },
      agentId: 'agent-donor-warmup',
      agentName: 'Donor Warm-Up Agent',
      role: 'Advancement',
      sourceSystem: 'Agent Platform',
      createdAt: '2024-01-15T08:45:00Z',
      updatedAt: '2024-01-15T08:46:00Z',
      slaDueAt: '2024-01-15T12:45:00Z',
      createdBy: 'agent',
      guardrailId: 'guardrail-tone',
      tags: ['tone', 'content-filter'],
    },
    {
      id: 'item-12',
      type: 'Task',
      severity: 'Medium',
      status: 'InProgress',
      title: 'Manual Review: Scholarship Eligibility',
      summary: 'Person flagged for scholarship review based on new criteria',
      person: {
        id: 'person-10',
        name: 'Christopher Lee',
        email: 'chris.lee@example.edu',
        externalId: 'STU-2024-023',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-high-intent-prospect',
      agentName: 'High-Intent Prospect Agent',
      role: 'Admissions',
      sourceSystem: 'Financial Aid System',
      createdAt: '2024-01-15T06:00:00Z',
      updatedAt: '2024-01-15T09:30:00Z',
      slaDueAt: '2024-01-16T18:00:00Z',
      createdBy: 'agent',
      assignedTo: 'user-456',
      tags: ['scholarship', 'financial-aid', 'review'],
    },
  ];
}

