import { AgentOpsItem } from './types';

export function getAdmissionsQueueItems(): AgentOpsItem[] {
  return [
    {
      id: 'admissions-item-1',
      type: 'Error',
      severity: 'Critical',
      status: 'Open',
      title: 'Missing Transcript - Critical',
      summary: 'Transcript Helper Agent unable to verify transcript for applicant. Transcript not found in SIS system.',
      person: {
        id: 'admissions-person-1',
        name: 'Sarah Chen',
        email: 'sarah.chen@example.edu',
        externalId: 'STU-2024-001',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-transcript-helper',
      agentName: 'Transcript Helper Agent',
      role: 'Admissions',
      sourceSystem: 'SIS',
      createdAt: '2024-01-15T10:30:00Z',
      updatedAt: '2024-01-15T10:35:00Z',
      slaDueAt: '2024-01-15T14:30:00Z',
      createdBy: 'system',
      tags: ['transcript', 'missing', 'api-error', 'sis-integration'],
    },
    {
      id: 'admissions-item-2',
      type: 'Error',
      severity: 'High',
      status: 'Open',
      title: 'Transcript Verification Failure',
      summary: 'Failed to verify transcript authenticity for applicant. Document format validation error.',
      person: {
        id: 'admissions-person-2',
        name: 'Michael Rodriguez',
        email: 'm.rodriguez@example.edu',
        externalId: 'STU-2024-042',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-transcript-helper',
      agentName: 'Transcript Helper Agent',
      role: 'Admissions',
      sourceSystem: 'SIS',
      createdAt: '2024-01-15T09:15:00Z',
      updatedAt: '2024-01-15T09:20:00Z',
      slaDueAt: '2024-01-15T13:15:00Z',
      createdBy: 'agent',
      tags: ['transcript', 'verification', 'validation'],
    },
    {
      id: 'admissions-item-3',
      type: 'Task',
      severity: 'High',
      status: 'Open',
      title: 'Follow-up: Incomplete Application (7+ days)',
      summary: 'High-intent prospect has not completed application form after 2 weeks of initial contact. Requires immediate follow-up.',
      person: {
        id: 'admissions-person-3',
        name: 'Emily Johnson',
        email: 'emily.j@example.edu',
        externalId: 'PROSP-2024-078',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-high-intent-prospect',
      agentName: 'High-Intent Prospect Agent',
      role: 'Admissions',
      sourceSystem: 'CRM',
      createdAt: '2024-01-14T14:00:00Z',
      updatedAt: '2024-01-15T09:00:00Z',
      slaDueAt: '2024-01-16T14:00:00Z',
      createdBy: 'agent',
      tags: ['task', 'follow-up', 'incomplete-app', 'prospect'],
    },
    {
      id: 'admissions-item-4',
      type: 'Escalation',
      severity: 'Critical',
      status: 'Open',
      title: 'Missing I-20 Document - Deadline in 3 Days',
      summary: 'International student missing I-20 and visa documents. Deadline approaching in 3 days. Requires urgent attention.',
      person: {
        id: 'admissions-person-4',
        name: 'Priya Patel',
        email: 'priya.patel@example.edu',
        externalId: 'STU-2024-089',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-international-visa',
      agentName: 'International Visa Docs Agent',
      role: 'Admissions',
      sourceSystem: 'SIS',
      createdAt: '2024-01-15T07:00:00Z',
      updatedAt: '2024-01-15T07:05:00Z',
      slaDueAt: '2024-01-15T12:00:00Z',
      createdBy: 'agent',
      tags: ['escalation', 'deadline', 'international', 'visa', 'i-20'],
    },
    {
      id: 'admissions-item-5',
      type: 'HumanReview',
      severity: 'High',
      status: 'InProgress',
      title: 'Human Review Required - Financial Aid Discussion',
      summary: 'Agent generated response discussing financial aid options that requires human approval before sending.',
      person: {
        id: 'admissions-person-5',
        name: 'David Kim',
        email: 'david.kim@example.edu',
        externalId: 'STU-2024-156',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-transcript-helper',
      agentName: 'Transcript Helper Agent',
      role: 'Admissions',
      sourceSystem: 'Agent Platform',
      createdAt: '2024-01-15T11:00:00Z',
      updatedAt: '2024-01-15T11:05:00Z',
      slaDueAt: '2024-01-15T13:00:00Z',
      createdBy: 'agent',
      assignedTo: 'user-123',
      tags: ['human-review', 'approval-needed', 'financial-aid'],
    },
    {
      id: 'admissions-item-6',
      type: 'Task',
      severity: 'High',
      status: 'Open',
      title: 'High-Intent Prospect - Application Deadline Reminder',
      summary: 'Prospect showing strong engagement signals. Application deadline in 5 days. Send personalized reminder.',
      person: {
        id: 'admissions-person-6',
        name: 'Alexandra Martinez',
        email: 'alex.martinez@example.edu',
        externalId: 'PROSP-2024-012',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-high-intent-prospect',
      agentName: 'High-Intent Prospect Agent',
      role: 'Admissions',
      sourceSystem: 'CRM',
      createdAt: '2024-01-15T08:30:00Z',
      updatedAt: '2024-01-15T08:35:00Z',
      slaDueAt: '2024-01-15T16:30:00Z',
      createdBy: 'agent',
      tags: ['task', 'prospect', 'deadline', 'application'],
    },
    {
      id: 'admissions-item-7',
      type: 'Error',
      severity: 'High',
      status: 'Open',
      title: 'API Connection Failure - Transcript Check',
      summary: 'Transcript Helper Agent failed to connect to SIS API during transcript verification for applicant.',
      person: {
        id: 'admissions-person-7',
        name: 'Robert Taylor',
        email: 'robert.taylor@example.edu',
        externalId: 'STU-2024-056',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-transcript-helper',
      agentName: 'Transcript Helper Agent',
      role: 'Admissions',
      sourceSystem: 'SIS',
      createdAt: '2024-01-15T10:00:00Z',
      updatedAt: '2024-01-15T10:01:00Z',
      slaDueAt: '2024-01-15T14:00:00Z',
      createdBy: 'system',
      tags: ['api-error', 'sis-integration', 'transcript'],
    },
    {
      id: 'admissions-item-8',
      type: 'Escalation',
      severity: 'Critical',
      status: 'Open',
      title: 'Visa Document Deadline - 2 Days Remaining',
      summary: 'International student visa document deadline approaching. Missing required documentation for I-20 processing.',
      person: {
        id: 'admissions-person-8',
        name: 'Yuki Tanaka',
        email: 'yuki.tanaka@example.edu',
        externalId: 'STU-2024-134',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-international-visa',
      agentName: 'International Visa Docs Agent',
      role: 'Admissions',
      sourceSystem: 'SIS',
      createdAt: '2024-01-15T06:30:00Z',
      updatedAt: '2024-01-15T06:35:00Z',
      slaDueAt: '2024-01-15T11:30:00Z',
      createdBy: 'agent',
      tags: ['escalation', 'deadline', 'international', 'visa', 'i-20'],
    },
    {
      id: 'admissions-item-9',
      type: 'Task',
      severity: 'Medium',
      status: 'InProgress',
      title: 'Scholarship Eligibility Review',
      summary: 'Applicant flagged for scholarship review based on new eligibility criteria. Requires manual verification.',
      person: {
        id: 'admissions-person-9',
        name: 'Christopher Lee',
        email: 'chris.lee@example.edu',
        externalId: 'STU-2024-023',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-high-intent-prospect',
      agentName: 'High-Intent Prospect Agent',
      role: 'Admissions',
      sourceSystem: 'Financial Aid System',
      createdAt: '2024-01-15T06:00:00Z',
      updatedAt: '2024-01-15T09:30:00Z',
      slaDueAt: '2024-01-16T18:00:00Z',
      createdBy: 'agent',
      assignedTo: 'user-456',
      tags: ['scholarship', 'financial-aid', 'review'],
    },
    {
      id: 'admissions-item-10',
      type: 'Guardrail',
      severity: 'High',
      status: 'Open',
      title: 'Sensitive Financial Information Detected',
      summary: 'Agent attempted to send message containing potentially sensitive financial aid information. Requires review.',
      person: {
        id: 'admissions-person-10',
        name: 'Lisa Anderson',
        email: 'lisa.anderson@example.edu',
        externalId: 'STU-2024-045',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-high-intent-prospect',
      agentName: 'High-Intent Prospect Agent',
      role: 'Admissions',
      sourceSystem: 'Agent Platform',
      createdAt: '2024-01-15T08:45:00Z',
      updatedAt: '2024-01-15T08:46:00Z',
      slaDueAt: '2024-01-15T12:45:00Z',
      createdBy: 'agent',
      guardrailId: 'guardrail-financial-info',
      tags: ['guardrail', 'content-filter', 'pii', 'financial-aid'],
    },
    {
      id: 'admissions-item-11',
      type: 'Error',
      severity: 'High',
      status: 'Open',
      title: 'Incomplete Transcript Submission',
      summary: 'Transcript uploaded but missing required pages. Applicant needs to resubmit complete transcript.',
      person: {
        id: 'admissions-person-11',
        name: 'James Wilson',
        email: 'james.wilson@example.edu',
        externalId: 'STU-2024-234',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-transcript-helper',
      agentName: 'Transcript Helper Agent',
      role: 'Admissions',
      sourceSystem: 'SIS',
      createdAt: '2024-01-15T09:30:00Z',
      updatedAt: '2024-01-15T09:35:00Z',
      slaDueAt: '2024-01-15T13:30:00Z',
      createdBy: 'agent',
      tags: ['transcript', 'incomplete', 'submission'],
    },
    {
      id: 'admissions-item-12',
      type: 'Task',
      severity: 'Medium',
      status: 'Open',
      title: 'High-Engagement Prospect - Follow-up Needed',
      summary: 'Prospect showing high engagement (multiple website visits, email opens). Schedule personalized outreach.',
      person: {
        id: 'admissions-person-12',
        name: 'Maria Garcia',
        email: 'maria.garcia@example.edu',
        externalId: 'PROSP-2024-089',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-high-intent-prospect',
      agentName: 'High-Intent Prospect Agent',
      role: 'Admissions',
      sourceSystem: 'CRM',
      createdAt: '2024-01-15T07:15:00Z',
      updatedAt: '2024-01-15T07:20:00Z',
      slaDueAt: '2024-01-16T07:15:00Z',
      createdBy: 'agent',
      tags: ['task', 'prospect', 'follow-up', 'high-engagement'],
    },
    {
      id: 'admissions-item-13',
      type: 'QuietHours',
      severity: 'Low',
      status: 'Snoozed',
      title: 'Message Blocked - Quiet Hours',
      summary: 'Attempted to send message outside of allowed hours (9 PM - 8 AM). Will retry during business hours.',
      person: {
        id: 'admissions-person-13',
        name: 'Daniel Brown',
        email: 'daniel.brown@example.edu',
        externalId: 'STU-2024-067',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-high-intent-prospect',
      agentName: 'High-Intent Prospect Agent',
      role: 'Admissions',
      sourceSystem: 'Agent Platform',
      createdAt: '2024-01-14T22:45:00Z',
      updatedAt: '2024-01-15T08:00:00Z',
      slaDueAt: '2024-01-15T10:00:00Z',
      createdBy: 'agent',
      tags: ['quiet-hours', 'scheduled'],
    },
    {
      id: 'admissions-item-14',
      type: 'DoNotEngage',
      severity: 'Medium',
      status: 'Open',
      title: 'Do Not Engage Rule Triggered',
      summary: 'Applicant has active DNE rule for email channel. Agent attempted to send email communication.',
      person: {
        id: 'admissions-person-14',
        name: 'Jennifer White',
        email: 'jennifer.white@example.edu',
        externalId: 'STU-2024-112',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-transcript-helper',
      agentName: 'Transcript Helper Agent',
      role: 'Admissions',
      sourceSystem: 'DNE System',
      createdAt: '2024-01-15T08:20:00Z',
      updatedAt: '2024-01-15T08:25:00Z',
      slaDueAt: '2024-01-15T12:20:00Z',
      createdBy: 'system',
      tags: ['dne', 'email-block'],
    },
    {
      id: 'admissions-item-15',
      type: 'Escalation',
      severity: 'High',
      status: 'Open',
      title: 'International Student - Document Verification Error',
      summary: 'International student document verification failed. I-20 processing blocked due to missing passport copy.',
      person: {
        id: 'admissions-person-15',
        name: 'Ahmed Hassan',
        email: 'ahmed.hassan@example.edu',
        externalId: 'STU-2024-178',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-international-visa',
      agentName: 'International Visa Docs Agent',
      role: 'Admissions',
      sourceSystem: 'SIS',
      createdAt: '2024-01-15T05:30:00Z',
      updatedAt: '2024-01-15T05:35:00Z',
      slaDueAt: '2024-01-15T13:30:00Z',
      createdBy: 'agent',
      tags: ['escalation', 'international', 'visa', 'verification'],
    },
    {
      id: 'admissions-item-16',
      type: 'Task',
      severity: 'High',
      status: 'InProgress',
      title: 'Application Review - Missing Recommendation Letter',
      summary: 'Application incomplete. Missing required recommendation letter. Send reminder to applicant.',
      person: {
        id: 'admissions-person-16',
        name: 'Sophie Martin',
        email: 'sophie.martin@example.edu',
        externalId: 'STU-2024-091',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-high-intent-prospect',
      agentName: 'High-Intent Prospect Agent',
      role: 'Admissions',
      sourceSystem: 'CRM',
      createdAt: '2024-01-14T16:00:00Z',
      updatedAt: '2024-01-15T10:00:00Z',
      slaDueAt: '2024-01-16T16:00:00Z',
      createdBy: 'agent',
      assignedTo: 'user-789',
      tags: ['task', 'application', 'incomplete-app', 'recommendation'],
    },
    {
      id: 'admissions-item-17',
      type: 'Error',
      severity: 'Critical',
      status: 'Open',
      title: 'Transcript Data Mismatch',
      summary: 'Transcript data does not match applicant records. GPA and course credits inconsistent. Requires manual review.',
      person: {
        id: 'admissions-person-17',
        name: 'Kevin Zhang',
        email: 'kevin.zhang@example.edu',
        externalId: 'STU-2024-145',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-transcript-helper',
      agentName: 'Transcript Helper Agent',
      role: 'Admissions',
      sourceSystem: 'SIS',
      createdAt: '2024-01-15T11:30:00Z',
      updatedAt: '2024-01-15T11:35:00Z',
      slaDueAt: '2024-01-15T15:30:00Z',
      createdBy: 'system',
      tags: ['transcript', 'data-mismatch', 'validation'],
    },
    {
      id: 'admissions-item-18',
      type: 'Guardrail',
      severity: 'Medium',
      status: 'Open',
      title: 'Tone Guardrail Triggered',
      summary: 'Agent response exceeded tone threshold (too formal). Response needs adjustment for prospect communication.',
      person: {
        id: 'admissions-person-18',
        name: 'Emma Thompson',
        email: 'emma.thompson@example.edu',
        externalId: 'PROSP-2024-156',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-high-intent-prospect',
      agentName: 'High-Intent Prospect Agent',
      role: 'Admissions',
      sourceSystem: 'Agent Platform',
      createdAt: '2024-01-15T09:15:00Z',
      updatedAt: '2024-01-15T09:16:00Z',
      slaDueAt: '2024-01-15T13:15:00Z',
      createdBy: 'agent',
      guardrailId: 'guardrail-tone',
      tags: ['guardrail', 'tone', 'content-filter'],
    },
  ];
}

export function getMockAgentOpsItems(): AgentOpsItem[] {
  return [
    {
      id: 'item-1',
      type: 'Error',
      severity: 'Critical',
      status: 'Open',
      title: 'API Connection Failure',
      summary: 'Agent "Transcript Helper" failed to connect to SIS API during transcript verification',
      person: {
        id: 'person-1',
        name: 'Sarah Chen',
        email: 'sarah.chen@example.edu',
        externalId: 'STU-2024-001',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-transcript-helper',
      agentName: 'Transcript Helper Agent',
      role: 'Admissions',
      sourceSystem: 'SIS',
      createdAt: '2024-01-15T10:30:00Z',
      updatedAt: '2024-01-15T10:35:00Z',
      slaDueAt: '2024-01-15T14:30:00Z',
      createdBy: 'system',
      tags: ['api-error', 'sis-integration'],
    },
    {
      id: 'item-2',
      type: 'Guardrail',
      severity: 'High',
      status: 'Open',
      title: 'Sensitive Content Detected',
      summary: 'Agent attempted to send message containing potentially sensitive financial information',
      person: {
        id: 'person-2',
        name: 'Michael Rodriguez',
        email: 'm.rodriguez@example.edu',
        externalId: 'STU-2024-042',
        primaryRole: 'Student Success',
      },
      agentId: 'agent-registration-requirements',
      agentName: 'Registration Requirements Agent',
      role: 'Registrar',
      sourceSystem: 'Agent Platform',
      createdAt: '2024-01-15T09:15:00Z',
      updatedAt: '2024-01-15T09:20:00Z',
      slaDueAt: '2024-01-15T13:15:00Z',
      createdBy: 'agent',
      guardrailId: 'guardrail-financial-info',
      tags: ['content-filter', 'pii'],
    },
    {
      id: 'item-3',
      type: 'QuietHours',
      severity: 'Low',
      status: 'Snoozed',
      title: 'Message Blocked - Quiet Hours',
      summary: 'Attempted to send message outside of allowed hours (9 PM - 8 AM)',
      person: {
        id: 'person-3',
        name: 'Emily Johnson',
        email: 'emily.j@example.edu',
        externalId: 'STU-2024-078',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-high-intent-prospect',
      agentName: 'High-Intent Prospect Agent',
      role: 'Admissions',
      sourceSystem: 'Agent Platform',
      createdAt: '2024-01-14T22:45:00Z',
      updatedAt: '2024-01-15T08:00:00Z',
      slaDueAt: '2024-01-15T10:00:00Z',
      createdBy: 'agent',
      tags: ['quiet-hours', 'scheduled'],
    },
    {
      id: 'item-4',
      type: 'DoNotEngage',
      severity: 'Medium',
      status: 'Resolved',
      title: 'Do Not Engage Rule Triggered',
      summary: 'Person has active DNE rule for email channel',
      person: {
        id: 'person-4',
        name: 'David Kim',
        email: 'david.kim@example.edu',
        externalId: 'STU-2023-156',
        primaryRole: 'Career Services',
      },
      agentId: 'agent-donor-warmup',
      agentName: 'Donor Warm-Up Agent',
      role: 'Advancement',
      sourceSystem: 'DNE System',
      createdAt: '2024-01-15T08:20:00Z',
      updatedAt: '2024-01-15T08:25:00Z',
      createdBy: 'system',
      tags: ['dne', 'email-block'],
    },
    {
      id: 'item-5',
      type: 'HumanReview',
      severity: 'High',
      status: 'InProgress',
      title: 'Human Review Required',
      summary: 'Agent generated response that requires human approval before sending',
      person: {
        id: 'person-1',
        name: 'Sarah Chen',
        email: 'sarah.chen@example.edu',
        externalId: 'STU-2024-001',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-transcript-helper',
      agentName: 'Transcript Helper Agent',
      role: 'Admissions',
      sourceSystem: 'Agent Platform',
      createdAt: '2024-01-15T11:00:00Z',
      updatedAt: '2024-01-15T11:05:00Z',
      slaDueAt: '2024-01-15T13:00:00Z',
      createdBy: 'agent',
      assignedTo: 'user-123',
      tags: ['human-review', 'approval-needed'],
    },
    {
      id: 'item-6',
      type: 'Escalation',
      severity: 'Critical',
      status: 'Open',
      title: 'Escalation: Missing Critical Documents',
      summary: 'Student missing I-20 and visa documents with deadline approaching in 3 days',
      person: {
        id: 'person-5',
        name: 'Priya Patel',
        email: 'priya.patel@example.edu',
        externalId: 'STU-2024-089',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-international-visa',
      agentName: 'International Visa Docs Agent',
      role: 'Admissions',
      sourceSystem: 'SIS',
      createdAt: '2024-01-15T07:00:00Z',
      updatedAt: '2024-01-15T07:05:00Z',
      slaDueAt: '2024-01-15T12:00:00Z',
      createdBy: 'agent',
      tags: ['escalation', 'deadline', 'international'],
    },
    {
      id: 'item-7',
      type: 'FrequencyCap',
      severity: 'Low',
      status: 'Open',
      title: 'Frequency Cap Reached',
      summary: 'Maximum messages per week limit reached for this person',
      person: {
        id: 'person-6',
        name: 'James Wilson',
        email: 'james.wilson@example.edu',
        externalId: 'STU-2023-234',
        primaryRole: 'Alumni Engagement',
      },
      agentId: 'agent-donor-warmup',
      agentName: 'Donor Warm-Up Agent',
      role: 'Advancement',
      sourceSystem: 'Agent Platform',
      createdAt: '2024-01-15T09:30:00Z',
      updatedAt: '2024-01-15T09:30:00Z',
      createdBy: 'system',
      tags: ['frequency-cap', 'rate-limit'],
    },
    {
      id: 'item-8',
      type: 'Task',
      severity: 'Medium',
      status: 'Open',
      title: 'Follow-up Required: Application Incomplete',
      summary: 'Prospect has not completed application form after 2 weeks of initial contact',
      person: {
        id: 'person-7',
        name: 'Alexandra Martinez',
        email: 'alex.martinez@example.edu',
        externalId: 'PROSP-2024-012',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-high-intent-prospect',
      agentName: 'High-Intent Prospect Agent',
      role: 'Admissions',
      sourceSystem: 'CRM',
      createdAt: '2024-01-14T14:00:00Z',
      updatedAt: '2024-01-15T09:00:00Z',
      slaDueAt: '2024-01-16T14:00:00Z',
      createdBy: 'agent',
      tags: ['task', 'follow-up', 'incomplete'],
    },
    {
      id: 'item-9',
      type: 'OnHold',
      severity: 'Low',
      status: 'Snoozed',
      title: 'Item On Hold - Awaiting Response',
      summary: 'Waiting for person to respond before proceeding with next action',
      person: {
        id: 'person-2',
        name: 'Michael Rodriguez',
        email: 'm.rodriguez@example.edu',
        externalId: 'STU-2024-042',
        primaryRole: 'Student Success',
      },
      agentId: 'agent-registration-requirements',
      agentName: 'Registration Requirements Agent',
      role: 'Registrar',
      sourceSystem: 'Agent Platform',
      createdAt: '2024-01-13T16:00:00Z',
      updatedAt: '2024-01-14T10:00:00Z',
      slaDueAt: '2024-01-17T16:00:00Z',
      createdBy: 'agent',
      tags: ['on-hold', 'awaiting-response'],
    },
    {
      id: 'item-10',
      type: 'Error',
      severity: 'High',
      status: 'Open',
      title: 'Data Validation Error',
      summary: 'Invalid email format detected in person record',
      person: {
        id: 'person-8',
        name: 'Robert Taylor',
        email: 'robert.taylor@example.edu',
        externalId: 'STU-2024-056',
        primaryRole: 'Career Services',
      },
      agentId: 'agent-donor-warmup',
      agentName: 'Donor Warm-Up Agent',
      role: 'Advancement',
      sourceSystem: 'CRM',
      createdAt: '2024-01-15T10:00:00Z',
      updatedAt: '2024-01-15T10:01:00Z',
      slaDueAt: '2024-01-15T14:00:00Z',
      createdBy: 'system',
      tags: ['data-quality', 'validation'],
    },
    {
      id: 'item-11',
      type: 'Guardrail',
      severity: 'Medium',
      status: 'Open',
      title: 'Tone Guardrail Triggered',
      summary: 'Agent response exceeded tone threshold (too formal)',
      person: {
        id: 'person-9',
        name: 'Lisa Anderson',
        email: 'lisa.anderson@example.edu',
        externalId: 'ALUM-2020-045',
        primaryRole: 'Alumni Engagement',
      },
      agentId: 'agent-donor-warmup',
      agentName: 'Donor Warm-Up Agent',
      role: 'Advancement',
      sourceSystem: 'Agent Platform',
      createdAt: '2024-01-15T08:45:00Z',
      updatedAt: '2024-01-15T08:46:00Z',
      slaDueAt: '2024-01-15T12:45:00Z',
      createdBy: 'agent',
      guardrailId: 'guardrail-tone',
      tags: ['tone', 'content-filter'],
    },
    {
      id: 'item-12',
      type: 'Task',
      severity: 'Medium',
      status: 'InProgress',
      title: 'Manual Review: Scholarship Eligibility',
      summary: 'Person flagged for scholarship review based on new criteria',
      person: {
        id: 'person-10',
        name: 'Christopher Lee',
        email: 'chris.lee@example.edu',
        externalId: 'STU-2024-023',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-high-intent-prospect',
      agentName: 'High-Intent Prospect Agent',
      role: 'Admissions',
      sourceSystem: 'Financial Aid System',
      createdAt: '2024-01-15T06:00:00Z',
      updatedAt: '2024-01-15T09:30:00Z',
      slaDueAt: '2024-01-16T18:00:00Z',
      createdBy: 'agent',
      assignedTo: 'user-456',
      tags: ['scholarship', 'financial-aid', 'review'],
    },
  ];
}

export function getMockAgentOpsItemsForWorkspace(workspaceId: string): AgentOpsItem[] {
  switch (workspaceId) {
    case 'admissions':
      return getAdmissionsQueueItems();
    // Future: Add other workspace-specific data
    // case 'registrar':
    //   return getRegistrarQueueItems();
    // case 'financial-aid':
    //   return getFinancialAidQueueItems();
    default:
      return getMockAgentOpsItems();
  }
}

