import { AgentOpsItem } from './types';

export function getAdmissionsQueueItems(): AgentOpsItem[] {
  return getMockAgentOpsItems().filter(item => item.role === 'Admissions');
}

export function getAdvancementPipelineQueueItems(): AgentOpsItem[] {
  // Return advancement items - for now, filter from general items
  // In a full implementation, this would have specific pipeline queue items
  return getMockAgentOpsItems().filter(item => item.role === 'Advancement');
}

export function getMockAgentOpsItemsForWorkspace(workspaceId: string): AgentOpsItem[] {
  switch (workspaceId) {
    case 'admissions':
      return getAdmissionsQueueItems();
    case 'advancement':
      return getAdvancementPipelineQueueItems();
    default:
      return getMockAgentOpsItems();
  }
}

export function getMockAgentOpsItems(): AgentOpsItem[] {
  return [
    {
      id: 'item-1',
      type: 'Error',
      severity: 'Critical',
      status: 'Open',
      title: 'API Connection Failure',
      summary: 'Agent "Transcript Helper" failed to connect to SIS API during transcript verification',
      person: {
        id: 'person-1',
        name: 'Sarah Chen',
        email: 'sarah.chen@example.edu',
        externalId: 'STU-2024-001',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-transcript-helper',
      agentName: 'Transcript Helper Agent',
      role: 'Admissions',
      sourceSystem: 'SIS',
      createdAt: '2024-01-15T10:30:00Z',
      updatedAt: '2024-01-15T10:35:00Z',
      slaDueAt: '2024-01-15T14:30:00Z',
      createdBy: 'system',
      tags: ['api-error', 'sis-integration'],
    },
    {
      id: 'item-2',
      type: 'Guardrail',
      severity: 'High',
      status: 'Open',
      title: 'Sensitive Content Detected',
      summary: 'Agent attempted to send message containing potentially sensitive financial information',
      person: {
        id: 'person-2',
        name: 'Michael Rodriguez',
        email: 'm.rodriguez@example.edu',
        externalId: 'STU-2024-042',
        primaryRole: 'Student Success',
      },
      agentId: 'agent-registration-requirements',
      agentName: 'Registration Requirements Agent',
      role: 'Registrar',
      sourceSystem: 'Agent Platform',
      createdAt: '2024-01-15T09:15:00Z',
      updatedAt: '2024-01-15T09:20:00Z',
      slaDueAt: '2024-01-15T13:15:00Z',
      createdBy: 'agent',
      guardrailId: 'guardrail-financial-info',
      tags: ['content-filter', 'pii'],
    },
    {
      id: 'item-3',
      type: 'QuietHours',
      severity: 'Low',
      status: 'Snoozed',
      title: 'Message Blocked - Quiet Hours',
      summary: 'Attempted to send message outside of allowed hours (9 PM - 8 AM)',
      person: {
        id: 'person-3',
        name: 'Emily Johnson',
        email: 'emily.j@example.edu',
        externalId: 'STU-2024-078',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-high-intent-prospect',
      agentName: 'High-Intent Prospect Agent',
      role: 'Admissions',
      sourceSystem: 'Agent Platform',
      createdAt: '2024-01-14T22:45:00Z',
      updatedAt: '2024-01-15T08:00:00Z',
      slaDueAt: '2024-01-15T10:00:00Z',
      createdBy: 'agent',
      tags: ['quiet-hours', 'scheduled'],
    },
    {
      id: 'item-4',
      type: 'DoNotEngage',
      severity: 'Medium',
      status: 'Resolved',
      title: 'Do Not Engage Rule Triggered',
      summary: 'Person has active DNE rule for email channel',
      person: {
        id: 'person-4',
        name: 'David Kim',
        email: 'david.kim@example.edu',
        externalId: 'STU-2023-156',
        primaryRole: 'Career Services',
      },
      agentId: 'agent-donor-warmup',
      agentName: 'Donor Warm-Up Agent',
      role: 'Advancement',
      sourceSystem: 'DNE System',
      createdAt: '2024-01-15T08:20:00Z',
      updatedAt: '2024-01-15T08:25:00Z',
      createdBy: 'system',
      tags: ['dne', 'email-block'],
    },
    {
      id: 'item-5',
      type: 'HumanReview',
      severity: 'High',
      status: 'InProgress',
      title: 'Human Review Required',
      summary: 'Agent generated response that requires human approval before sending',
      person: {
        id: 'person-1',
        name: 'Sarah Chen',
        email: 'sarah.chen@example.edu',
        externalId: 'STU-2024-001',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-transcript-helper',
      agentName: 'Transcript Helper Agent',
      role: 'Admissions',
      sourceSystem: 'Agent Platform',
      createdAt: '2024-01-15T11:00:00Z',
      updatedAt: '2024-01-15T11:05:00Z',
      slaDueAt: '2024-01-15T13:00:00Z',
      createdBy: 'agent',
      assignedTo: 'user-123',
      tags: ['human-review', 'approval-needed'],
    },
    {
      id: 'item-6',
      type: 'Escalation',
      severity: 'Critical',
      status: 'Open',
      title: 'Escalation: Missing Critical Documents',
      summary: 'Student missing I-20 and visa documents with deadline approaching in 3 days',
      person: {
        id: 'person-5',
        name: 'Priya Patel',
        email: 'priya.patel@example.edu',
        externalId: 'STU-2024-089',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-international-visa',
      agentName: 'International Visa Docs Agent',
      role: 'Admissions',
      sourceSystem: 'SIS',
      createdAt: '2024-01-15T07:00:00Z',
      updatedAt: '2024-01-15T07:05:00Z',
      slaDueAt: '2024-01-15T12:00:00Z',
      createdBy: 'agent',
      tags: ['escalation', 'deadline', 'international'],
    },
    {
      id: 'item-7',
      type: 'FrequencyCap',
      severity: 'Low',
      status: 'Open',
      title: 'Frequency Cap Reached',
      summary: 'Maximum messages per week limit reached for this person',
      person: {
        id: 'person-6',
        name: 'James Wilson',
        email: 'james.wilson@example.edu',
        externalId: 'STU-2023-234',
        primaryRole: 'Alumni Engagement',
      },
      agentId: 'agent-donor-warmup',
      agentName: 'Donor Warm-Up Agent',
      role: 'Advancement',
      sourceSystem: 'Agent Platform',
      createdAt: '2024-01-15T09:30:00Z',
      updatedAt: '2024-01-15T09:30:00Z',
      createdBy: 'system',
      tags: ['frequency-cap', 'rate-limit'],
    },
    {
      id: 'item-8',
      type: 'Task',
      severity: 'Medium',
      status: 'Open',
      title: 'Follow-up Required: Application Incomplete',
      summary: 'Prospect has not completed application form after 2 weeks of initial contact',
      person: {
        id: 'person-7',
        name: 'Alexandra Martinez',
        email: 'alex.martinez@example.edu',
        externalId: 'PROSP-2024-012',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-high-intent-prospect',
      agentName: 'High-Intent Prospect Agent',
      role: 'Admissions',
      sourceSystem: 'CRM',
      createdAt: '2024-01-14T14:00:00Z',
      updatedAt: '2024-01-15T09:00:00Z',
      slaDueAt: '2024-01-16T14:00:00Z',
      createdBy: 'agent',
      tags: ['task', 'follow-up', 'incomplete'],
    },
    {
      id: 'item-9',
      type: 'OnHold',
      severity: 'Low',
      status: 'Snoozed',
      title: 'Item On Hold - Awaiting Response',
      summary: 'Waiting for person to respond before proceeding with next action',
      person: {
        id: 'person-2',
        name: 'Michael Rodriguez',
        email: 'm.rodriguez@example.edu',
        externalId: 'STU-2024-042',
        primaryRole: 'Student Success',
      },
      agentId: 'agent-registration-requirements',
      agentName: 'Registration Requirements Agent',
      role: 'Registrar',
      sourceSystem: 'Agent Platform',
      createdAt: '2024-01-13T16:00:00Z',
      updatedAt: '2024-01-14T10:00:00Z',
      slaDueAt: '2024-01-17T16:00:00Z',
      createdBy: 'agent',
      tags: ['on-hold', 'awaiting-response'],
    },
    {
      id: 'item-10',
      type: 'Error',
      severity: 'High',
      status: 'Open',
      title: 'Data Validation Error',
      summary: 'Invalid email format detected in person record',
      person: {
        id: 'person-8',
        name: 'Robert Taylor',
        email: 'robert.taylor@example.edu',
        externalId: 'STU-2024-056',
        primaryRole: 'Career Services',
      },
      agentId: 'agent-donor-warmup',
      agentName: 'Donor Warm-Up Agent',
      role: 'Advancement',
      sourceSystem: 'CRM',
      createdAt: '2024-01-15T10:00:00Z',
      updatedAt: '2024-01-15T10:01:00Z',
      slaDueAt: '2024-01-15T14:00:00Z',
      createdBy: 'system',
      tags: ['data-quality', 'validation'],
    },
    {
      id: 'item-11',
      type: 'Guardrail',
      severity: 'Medium',
      status: 'Open',
      title: 'Tone Guardrail Triggered',
      summary: 'Agent response exceeded tone threshold (too formal)',
      person: {
        id: 'person-9',
        name: 'Lisa Anderson',
        email: 'lisa.anderson@example.edu',
        externalId: 'ALUM-2020-045',
        primaryRole: 'Alumni Engagement',
      },
      agentId: 'agent-donor-warmup',
      agentName: 'Donor Warm-Up Agent',
      role: 'Advancement',
      sourceSystem: 'Agent Platform',
      createdAt: '2024-01-15T08:45:00Z',
      updatedAt: '2024-01-15T08:46:00Z',
      slaDueAt: '2024-01-15T12:45:00Z',
      createdBy: 'agent',
      guardrailId: 'guardrail-tone',
      tags: ['tone', 'content-filter'],
    },
    {
      id: 'item-12',
      type: 'Task',
      severity: 'Medium',
      status: 'InProgress',
      title: 'Manual Review: Scholarship Eligibility',
      summary: 'Person flagged for scholarship review based on new criteria',
      person: {
        id: 'person-10',
        name: 'Christopher Lee',
        email: 'chris.lee@example.edu',
        externalId: 'STU-2024-023',
        primaryRole: 'Admissions',
      },
      agentId: 'agent-high-intent-prospect',
      agentName: 'High-Intent Prospect Agent',
      role: 'Admissions',
      sourceSystem: 'Financial Aid System',
      createdAt: '2024-01-15T06:00:00Z',
      updatedAt: '2024-01-15T09:30:00Z',
      slaDueAt: '2024-01-16T18:00:00Z',
      createdBy: 'agent',
      assignedTo: 'user-456',
      tags: ['scholarship', 'financial-aid', 'review'],
    },
  ];
}

