'use client';

import React from 'react';
import Link from 'next/link';
import { AgentOpsItem } from '@/lib/agent-ops/types';
import { FontAwesomeIcon } from '@/components/ui/font-awesome-icon';
import { Button } from '@/components/ui/button';
import type { QueueAction } from '@/components/ai-assistants/agent-ops/queue/QueueList';
import type { QueueDetailRendererProps } from './registry';

function formatTime(iso: string) {
  try {
    const d = new Date(iso);
    return d.toLocaleString('en-US', { dateStyle: 'short', timeStyle: 'short' });
  } catch {
    return iso;
  }
}

/**
 * Detail renderer for AGENT_BLOCKED_ACTION queue items.
 * Shows what was blocked and why (guardrail/narrative).
 */
export function AgentBlockedActionDetail({
  item,
  onAction,
  onNavigateToPerson,
  basePath,
}: QueueDetailRendererProps) {
  const payload = item.payload as { actionLogId?: string; reason?: string; topicDetected?: string } | undefined;
  const agentId = item.agentId;
  const runId = item.runId;
  const actionLogId = payload?.actionLogId;

  const handleAction = (action: QueueAction) => {
    if (onAction) onAction(item.id, action);
  };

  return (
    <div className="h-full overflow-y-auto">
      <div className="p-6 space-y-6">
        <header className="pb-4 border-b border-gray-200">
          <div className="flex items-center gap-2 mb-2">
            <span className="text-xs uppercase tracking-wide text-gray-500">Blocked action</span>
            <span className="text-xs text-gray-400">•</span>
            <span className="text-xs text-gray-500">{item.severity}</span>
            {item.agentName && (
              <>
                <span className="text-xs text-gray-400">•</span>
                <span className="text-xs text-gray-500">{item.agentName}</span>
              </>
            )}
          </div>
          <h2 className="text-lg font-semibold text-gray-900 mb-1">{item.title}</h2>
          <p className="text-sm text-gray-600 mb-3">{item.summary}</p>
          <p className="text-xs text-gray-500 italic">Generated by AI Agent</p>
          {item.runId && (
            <p className="text-xs text-gray-400 mt-1">
              Run ID: <span className="font-mono">{item.runId}</span>
              {' · '}
              {formatTime(item.createdAt)}
            </p>
          )}
          <div className="mt-2 flex flex-wrap gap-2 items-center">
            <span className="px-2 py-1 rounded text-xs font-medium bg-amber-50 text-amber-700">{item.status}</span>
            {item.slaStatus === 'BREACHED' && (
              <span className="px-2 py-1 rounded text-xs font-medium bg-red-100 text-red-800">SLA Breached</span>
            )}
            {item.slaStatus === 'AT_RISK' && (
              <span className="px-2 py-1 rounded text-xs font-medium bg-amber-100 text-amber-800">At risk</span>
            )}
          </div>
        </header>

        {(agentId || runId || actionLogId) && basePath && (
          <section>
            <h3 className="text-sm font-semibold text-gray-900 mb-2">Links</h3>
            <div className="flex flex-wrap gap-2">
              {agentId && (
                <Link href={`${basePath}/agents/${agentId}`} className="text-xs text-indigo-600 hover:underline flex items-center gap-1">
                  <FontAwesomeIcon icon="fa-solid fa-robot" className="h-3 w-3" /> View Agent
                </Link>
              )}
              {agentId && runId && (
                <Link href={`${basePath}/agents/${agentId}?tab=runs&runId=${runId}`} className="text-xs text-indigo-600 hover:underline flex items-center gap-1">
                  <FontAwesomeIcon icon="fa-solid fa-play" className="h-3 w-3" /> View Run
                </Link>
              )}
              {agentId && actionLogId && (
                <Link href={`${basePath}/agents/${agentId}?tab=actions&actionLogId=${actionLogId}`} className="text-xs text-indigo-600 hover:underline flex items-center gap-1">
                  <FontAwesomeIcon icon="fa-solid fa-list" className="h-3 w-3" /> View Action Log
                </Link>
              )}
            </div>
          </section>
        )}

        <section>
          <h3 className="text-sm font-semibold text-gray-900 mb-2">Why it was blocked</h3>
          <div className="border border-amber-200 rounded-lg p-4 bg-amber-50">
            <p className="text-sm text-gray-900">{item.summary}</p>
            {payload?.reason && (
              <p className="text-xs text-gray-600 mt-2">
                Reason: <code className="bg-amber-100 px-1 rounded">{payload.reason}</code>
              </p>
            )}
            {item.guardrailId && (
              <p className="text-xs text-gray-500 mt-1">Guardrail: {item.guardrailId}</p>
            )}
          </div>
        </section>

        {item.person && (
          <section>
            <h3 className="text-sm font-semibold text-gray-900 mb-2">Person</h3>
            <div className="bg-gray-50 rounded-lg p-3 flex items-center justify-between">
              <span className="text-sm text-gray-900">{item.person.name}</span>
              {onNavigateToPerson && (
                <Button variant="outline" size="sm" onClick={() => onNavigateToPerson(item.person!.id)} className="text-xs">
                  View profile
                </Button>
              )}
            </div>
          </section>
        )}

        <section className="pt-4 border-t border-gray-200 flex flex-wrap gap-2">
          <Button size="sm" onClick={() => handleAction('resolve')} className="text-xs">
            <FontAwesomeIcon icon="fa-solid fa-check" className="h-3 w-3 mr-1.5" />
            Resolve
          </Button>
          <Button size="sm" variant="outline" onClick={() => handleAction('snooze')} className="text-xs">
            <FontAwesomeIcon icon="fa-solid fa-clock" className="h-3 w-3 mr-1.5" />
            Snooze
          </Button>
          <Button size="sm" variant="outline" onClick={() => handleAction('skip')} className="text-xs">
            <FontAwesomeIcon icon="fa-solid fa-forward" className="h-3 w-3 mr-1.5" />
            Skip
          </Button>
        </section>
      </div>
    </div>
  );
}
